theme: jekyll-theme-midnight
title: "UB3R-B0T"
description: "Everything you want and don't want to know about UB3R-B0T"

lang: en

repository: moiph/ub3r-b0t-docs
repository_tree: master

toc: true

plugins:
  - jekyll-remote-theme
