remote_theme: kitian616/jekyll-text-theme
title: "UB3R-B0T"
description: "Everything you want and don't want to know about UB3R-B0T"
text_skin: dark
highlight_theme: default

toc:
  selectors: # "h1,h2,h3" (default)

defaults:
  - scope:
      path: ""
    values:
      layout: article
      aside:
        toc: true
      show_edit_on_github: true
